

on:
  workflow_dispatch:

name: Check for CRAN

jobs:

  rcmdcheck:

    strategy:
      fail-fast: true
      matrix:
        config:
          - { R: "devel", os: "ubuntu-latest"}
          - { R: "release", os: "macos-latest"}
          - { R: "release", os: "windows-latest"}
          - { R: "release", os: "ubuntu-latest"}

    runs-on: ${{ matrix.config.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_TEST_FULL: 'FALSE' 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        id: install-r
        with:
          r-version: ${{ matrix.config.R }}

      - name: Prevent Windows from installing non-binary packages
        if: ${{ matrix.config.os == 'windows-latest'  }}
        shell: bash
        run: |
          echo 'options(install.packages.check.source = "no")' >>  .Rprofile

      - name: Install R package dependencies
        shell: Rscript {0}
        run: |
          options("repos" = list("CRAN" = "https://www.stats.bris.ac.uk/R/"))
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Check
        uses: ./.github/actions/rcmdcheck
        with:
          slim: false
